import type { FakePrismaClient } from './fakePrisma';

/**
 * Default content seed for the in-memory Prisma. Field names mirror the Prisma
 * schema (snake-cased in Postgres, camel in the client); the fake client stores
 * records as-is, so controllers that `include`/`select` nested relations just
 * see the flat record.
 */
export function buildSeed() {
  return {
    cefrLevel: [
      { id: 'level-1', code: 'A1', title: 'Beginner', sortOrder: 1 },
      { id: 'level-2', code: 'A2', title: 'Elementary', sortOrder: 2 },
    ],
    language: [
      {
        id: 'lang-1',
        code: 'es',
        name: 'Spanish',
        nativeName: 'Español',
        direction: 'LTR',
        flagEmoji: '🇪🇸',
        status: 'active',
        _count: { lessons: 2 },
        units: [{ id: 'unit-1', levelId: 'level-1' }],
      },
      {
        id: 'lang-2',
        code: 'ar',
        name: 'Arabic',
        nativeName: 'العربية',
        direction: 'RTL',
        flagEmoji: '🇸🇦',
        status: 'active',
        _count: { lessons: 1 },
        units: [],
      },
    ],
    unit: [
      {
        id: 'unit-1',
        languageId: 'lang-1',
        levelId: 'level-1',
        code: 'u1',
        title: 'Greetings',
        description: 'Say hello',
        sortOrder: 1,
      },
      {
        id: 'unit-2',
        languageId: 'lang-2',
        levelId: 'level-2',
        code: 'u2',
        title: 'Basics',
        description: 'First words',
        sortOrder: 1,
      },
    ],
    lesson: [
      {
        id: 'lesson-1',
        title: 'Hola',
        description: 'Hi',
        category: 'vocabulary',
        xpReward: 20,
        orderIndex: 1,
        isPublished: true,
        languageId: 'lang-1',
        levelId: 'level-1',
        unitId: 'unit-1',
        tags: ['greeting'],
        language: { code: 'es' },
        level: { code: 'A1' },
      },
      {
        id: 'lesson-2',
        title: 'مرحبا',
        description: 'Marhaba',
        category: 'vocabulary',
        xpReward: 20,
        orderIndex: 1,
        isPublished: true,
        languageId: 'lang-2',
        levelId: 'level-2',
        unitId: 'unit-2',
        tags: [],
        language: { code: 'ar' },
        level: { code: 'A2' },
      },
      {
        id: 'lesson-hidden',
        title: 'Hidden',
        description: 'not published',
        category: 'vocabulary',
        xpReward: 10,
        orderIndex: 9,
        isPublished: false,
        languageId: 'lang-1',
        levelId: 'level-1',
        unitId: 'unit-1',
        tags: [],
        language: { code: 'es' },
        level: { code: 'A1' },
      },
    ],
    exercise: [
      {
        id: 'ex-1',
        lessonId: 'lesson-1',
        type: 'vocabulary',
        prompt: 'Say hello',
        targetText: 'Hola',
        optionsJson: null,
        correctAnswer: 'Hola',
        audioUrl: null,
        phoneticText: 'o-la',
        explanation: null,
        passageText: null,
        sortOrder: 1,
        isPublished: true,
      },
      {
        id: 'ex-hidden',
        lessonId: 'lesson-1',
        type: 'vocabulary',
        prompt: 'Hidden',
        targetText: 'X',
        optionsJson: null,
        correctAnswer: 'X',
        audioUrl: null,
        phoneticText: null,
        explanation: null,
        passageText: null,
        sortOrder: 9,
        isPublished: false,
      },
    ],
    vocabulary: [
      {
        id: 'vocab-1',
        languageId: 'lang-1',
        language: { code: 'es' },
        word: 'hola',
        translation: 'hello',
        exampleSentence: null,
        exampleTranslation: null,
        phonetic: 'o-la',
        category: 'Greetings',
      },
      {
        id: 'vocab-2',
        languageId: 'lang-1',
        language: { code: 'es' },
        word: 'favorito',
        translation: 'favorite',
        exampleSentence: null,
        exampleTranslation: null,
        phonetic: '',
        category: 'General',
      },
    ],
    flashcard: [
      {
        id: 'fc-1',
        languageId: 'lang-1',
        language: { code: 'es' },
        frontWord: 'hola',
        backTranslation: 'hello',
        exampleSentence: null,
        phonetic: 'o-la',
        intervalDays: 1,
        isMastered: false,
        nextReviewAt: '2026-01-01T00:00:00.000Z',
      },
    ],
    grammarRule: [
      {
        id: 'rule-1',
        languageId: 'lang-1',
        language: { code: 'es' },
        levelId: 'level-1',
        level: { code: 'A1' },
        title: 'Articles',
        summary: 'el/la',
        fullRuleText: 'Spanish nouns have gender.',
        exampleSentence: 'la casa',
        exampleTranslation: 'the house',
      },
    ],
    achievement: [
      {
        id: 'ach-1',
        title: 'First lesson',
        description: 'Finish one lesson',
        iconName: 'star',
        rewardXp: 10,
        conditionType: 'lessons',
        conditionValue: 1,
        isActive: true,
      },
    ],
    user: [
      {
        id: 'user-1',
        username: 'alice',
        email: 'alice@example.com',
        passwordHash: 'hashed:secret123',
        avatarUrl: null,
        nativeLanguageId: 'lang-1',
        xp: 100,
        coins: 10,
        streakCount: 2,
        lastActiveDate: null,
        dailyGoalXp: 50,
        todayXp: 20,
        createdAt: '2026-01-01T00:00:00.000Z',
      },
    ],
    userLanguage: [
      {
        id: 'ul-1',
        userId: 'user-1',
        languageId: 'lang-1',
        targetLevel: 'A1',
        isPrimary: true,
      },
    ],
    userLessonProgress: [],
    userExerciseProgress: [],
    userVocabularyProgress: [],
    userAchievement: [],
    aiUsage: [],
    chatMessage: [],
  };
}

export type Seed = ReturnType<typeof buildSeed>;

/** True when `client` is the fake (integration) client rather than a real Prisma instance. */
export function isFakePrisma(client: unknown): client is FakePrismaClient {
  return Boolean(client && typeof (client as FakePrismaClient).reset === 'function');
}